### ISSUE TITLE
architecture discussion

### ISSUE THREAD

**Issue by ghost** [oceanmodeling/searvey#12]
As far as the abstraction architecture goes, I propose that the data getters be abstracted into at least 2 layers:
1. the **data source** layer - this should encompass specific data sources, and methods that query their APIs. Data sources should output an (at least) semi-standardized data format, such as `geopandas.GeoDataFrame` or `xarray.Dataset`.
2. the **data product** layer - this should encompass abstractions of data products (e.g. water level, water velocity, storm track, etc.). The output of this layer should be much more standardized as this is what the end user actually cares about.

The key point here is that one data source may contribute to multiple data products, and one data product might be contributed to by multiple data sources. Separating into these distinct layers would make it much easier to maintain data sources and add new sources and / or products in the future.

**Comment by zacharyburnettNOAA** [comment]
@SorooshMani-NOAA @brey

**Comment by SorooshMani-NOAA** [comment]
@zacharyburnettNOAA do you have something like this in mind (ignore the missing arrows for other combinations!)?
![image](https://user-images.githubusercontent.com/77082694/154763744-b58782c8-379b-423b-99ab-f44af809c426.png)

Or do you mean that those concrete objects are created by factories and user interacts with the factories? (I don't feel like drawing factory here, too much work!)

**Comment by brey** [comment]
Generally, I agree with the concept. In fact the data sources DataFrame is a product by itself. However, as you said, each source provides a number of products. How one can tabulate these products for quick reference is an issue. Will it be a metadata on the source? Will they be parsed on the fly through the appropriate API? How can we standardise the products across providers?

**Comment by zacharyburnettNOAA** [comment]
@SorooshMani-NOAA yes, exactly like that. We can accomplish all of this through careful usage of inheritance, and that also provides an easy interface to implement new data sources later using `@abc.abstractmethod`

@brey I think the data abstraction layer should be transparently handling the underlying data source layer, but you're right that might become very complicated very fast

**Comment by pmav99** [comment]
Closing
