### ISSUE TITLE
Source catalogs 

### ISSUE THREAD

**Issue by brey** [oceanmodeling/searvey#13]
I have used, in the past, [this](https://gist.github.com/68c8992b89bd41d128c01e7f9a08ab81) procedure to create the catalogs from providers' websites. 

We need to review, possibly update and include something similar to `searvey`. 

@yosoyjay @zacharyburnettNOAA @pmav99

**Comment by yosoyjay** [comment]
It might be a little cleaner to use the [ERDDAP](https://uhslc.soest.hawaii.edu/erddap/index.html) server to query and select the data.

It looks like there is also a [private REST api](http://www.ioc-sealevelmonitoring.org/service.php) that one can request access to.

**Comment by brey** [comment]
Closing this one in favour of #15
