### ISSUE TITLE
get active status from IOC-UNESCO stations

### ISSUE THREAD

**Issue by carolakaiser** [oceanmodeling/searvey#131]
Hey guys, 
I am looking for a way to get the status of the IOC-UNESCO stations (active or not) for real-time data retrieval.
There is the overview page here https://www.ioc-sealevelmonitoring.org/ and the status for each station is given there. What I am trying to accomplish is to get a list of station IDs that have been active within the last 2 days.
I cannot really remember but do you support this? And if so, would you maybe have a short line of code how to get into this?

**Comment by pmav99** [comment]
Hi Carola, do you mean something like this?
```
import searvey
import datetime

meta = searvey.get_stations(activity_threshold=datetime.timedelta(days=2))
meta[meta.provider == "IOC"]
```
For the record, this was discussed here: https://github.com/oceanmodeling/searvey/issues/41

**Comment by carolakaiser** [comment]
Yes, that looks perfect.

**Comment by pmav99** [comment]
you can also do it like this:
``` python
meta = searvey.get_stations(providers=[searvey.Provider.IOC], activity_threshold=datetime.timedelta(days=2))
# or even
meta = searvey.get_stations(providers=searvey.Provider.IOC, activity_threshold=datetime.timedelta(days=2))
```
which should be slightly faster, too, since it doesn't retrieve the metadata of the other providers.
