### ISSUE TITLE
Add USGS storm based time series source

### ISSUE THREAD

**Issue by saeed-moghimi-noaa** [oceanmodeling/searvey#14]
@zacharyburnettNOAA  @SorooshMani-NOAA 

Adding USGS timeseries from https://stn.wim.usgs.gov/FEV/#FlorenceSep2018

This is a code I got from @flackdl . See this repo developed by Danny as well: https://github.com/flackdl/cwwed .

``` 
import os
import re
import sys
import errno
import requests
from io import open

EVENT_ID_MATTHEW = 135  # default

# capture an event_id from the command line, defaulting to Matthew
EVENT_ID = sys.argv[1] if len(sys.argv) > 1 else EVENT_ID_MATTHEW

# file type "data"
# https://stn.wim.usgs.gov/STNServices/FileTypes.json
FILE_TYPE_DATA = 2

# deployment types
# https://stn.wim.usgs.gov/STNServices/DeploymentTypes.json
DEPLOYMENT_TYPE_WATER_LEVEL = 1
DEPLOYMENT_TYPE_WAVE_HEIGHT = 2
DEPLOYMENT_TYPE_BAROMETRIC = 3
DEPLOYMENT_TYPE_TEMPERATURE = 4
DEPLOYMENT_TYPE_WIND_SPEED = 5
DEPLOYMENT_TYPE_HUMIDITY = 6
DEPLOYMENT_TYPE_AIR_TEMPERATURE = 7
DEPLOYMENT_TYPE_WATER_TEMPERATURE = 8
DEPLOYMENT_TYPE_RAPID_DEPLOYMENT = 9

# create output directory
output_directory = 'output'
try:
    os.makedirs(output_directory)
except OSError as exception:
    if exception.errno != errno.EEXIST:
        raise

# fetch event data files
files_req = requests.get('https://stn.wim.usgs.gov/STNServices/Events/{}/Files.json'.format(EVENT_ID))
files_req.raise_for_status()
files_json = files_req.json()

# fetch event sensors
sensors_req = requests.get('https://stn.wim.usgs.gov/STNServices/Events/{}/Instruments.json'.format(EVENT_ID))
sensors_req.raise_for_status()
sensors_json = sensors_req.json()

# filter sensors down to barometric ones
barometric_sensors = [sensor for sensor in sensors_json if sensor.get('deployment_type_id') == DEPLOYMENT_TYPE_BAROMETRIC]

# print file urls for barometric sensors for this event
for file in files_json:
    if file['filetype_id'] == FILE_TYPE_DATA and file['instrument_id'] in [s['instrument_id'] for s in barometric_sensors]:

        file_url = 'https://stn.wim.usgs.gov/STNServices/Files/{}/item'.format(file['file_id'])

        # fetch the actual file
        file_req = requests.get(file_url, stream=True)

        # capture the filename from the headers so we can save it appropriately
        match = re.match('.*filename="(?P<filename>.*)"', file_req.headers['Content-Disposition'])
        if match:
            filename = match.group('filename')
        else:
            filename = '{}.unknown'.format(file['file_id'])
            print('COULD NOT FIND "filename" in header, saving as {}'.format(filename))

        print('{}\t\t({})'.format(filename, file_url))

        with open('{}/{}'.format(output_directory, filename), 'wb') as f:
            for chunk in file_req.iter_content(chunk_size=1024):
                f.write(chunk)
```

**Comment by zacharyburnettNOAA** [comment]
thanks!

**Comment by saeed-moghimi-noaa** [comment]
Thanks to  @flackdl  just share the location of the latest file:
 https://github.com/flackdl/cwwed/blob/ad39f0e9bea6a0a3bdbc937fea41994f4ed359ba/scripts/usgs.py

**Comment by saeed-moghimi-noaa** [comment]
Thanks @zacharyburnettNOAA . See the email I just sent to Danny.

**Comment by brey** [comment]
@SorooshMani-NOAA provided some input via email. I repost here for completeness:

Today I noticed this package on GitHub: [https://github.com/USGS-python/dataretrieval](https://urldefense.com/v3/__https:/github.com/USGS-python/dataretrieval__;!!DOxrgLBm!ABqNaXuatc0p3rFNcnzBaPkCfC_Tow6-kL8smUwS8BZ9aYHqryiftF93j41XxRUZ3DixPvxlZLuAbVw4BiPwlVU79BYfeubocw$)

I was wondering if this retrieves the same data that you were interested in or if there's another USGS database that you'd like to query? 

This ones seems to have the following data available for retrieval:
instantaneous values (iv)
daily values (dv)
statistics (stat)
site info (site)
discharge peaks (peaks)
discharge measurements (measurements)
water quality samples (qwdata)

which seems to be what the water services REST API provides:
https://waterservices.usgs.gov/rest/


George, if this is the same database the Jack is interested in, does it make sense to add a "normalization" wrapper on top of the `dataretrieval` package or should `searvey` directly use REST API?

**Comment by brey** [comment]
I looked a bit into `dataretrieval` and looks good. It already has users, they are considering doing a conda package 
(see issue 44 therein) and the lead developer works for USGS which is beneficial for updates and access. 

If it exposes all the data, then we can make a wrapper and use it as upstream dependency. 

We can also invite Timothy Hodson to a meeting and discuss it.

**Comment by SorooshMani-NOAA** [comment]
Documenting relevant email discussions (added typo fix and emphasis):
> [...] CSDL [...] is interested in the following observations in support of the coastal application teams modeling work for NOAA products and services:
> 
> - Surface water level
> - Water level datums, relative and geodetic observations
> - Water temperature
> - Water salinity
> - Water currents
> 
> I am primarily interested in **datum points** in support of navigation products and services; and, _where unavailable_, interested in the **surface water levels** to formulate new datums.  The challenge of course is to have `searvey` assemble available observations sourced from NOAA, IOC, USGS, etc. into the **normalized categories** above.  In the case of USGS, the number of [potentially] available parameters to sort out from their observation sites looks especially large—so any software API / wrapper that makes that easier, maintainable, etc. should be leveraged:
> 
> https://waterdata.usgs.gov/nwis/uv?referred_module=sw&search_criteria=multiple_site_no&submitted_form=introduction

@brey @pmav99 I can't find the other ticket where we discussed normalization and/or standardization of the outputs. Given the quoted email above, how would you approach adding getter functions? Do we have a template to follow?

**Comment by pmav99** [comment]
We don't have a "template". I added some thoughts of how the API could/should be in the wiki: https://github.com/oceanmodeling/searvey/wiki/API-design
but feel free to open a new ticket to further discuss this.

**Comment by brey** [comment]
I understand the point but I wonder if we should bring this to the attention of Timothy first (with an issue on `dataretrieval`) and see what he has to say. Having said that I leave it up to you guys.

**Comment by SorooshMani-NOAA** [comment]
I think it would be better to do what you suggest. I already created an issue here https://github.com/USGS-python/dataretrieval/issues/59. In the last meeting only two of us were present, so I just wanted to relay what was discussed. I haven't yet implemented anything for USGS.

**Comment by mroberge** [comment]
There are a variety of Python packages that use the USGS API. I set up a discussion among the authors here: https://github.com/mroberge/hydrofunctions/issues/79

- Taher Chegini @cheginit just added some elegant code to his [HyRiver](https://github.com/cheginit/HyRiver) package that deals with timezone information from the USGS metadata.
- my [hydrofunctions](https://github.com/mroberge/hydrofunctions) requests data, stores the original response, and formats it into dataframes upon request. My plan is to offer more ways to organize the dataframe in the future: a 'tidy' format, wide, and multiindex.

**Comment by SorooshMani-NOAA** [comment]
Thank you @mroberge this information is very helpful.

**Comment by SorooshMani-NOAA** [comment]
I just realized that the `get_iv` metadata item in the returned tuple can include information about the parameter code or site. I though that the metadata only includes header or url information, but if the right arguments are passed, more information is extracted and included. I think the main question now is how much we want to keep the data from REST API untouched?

For IOC and COOPS stations we pretty much return whatever is provided by the web services, but for USGS NWIS we have to do so transformation either way. Can we then just take output of `dataretrieval` (or even one of the other packages from https://github.com/oceanmodeling/searvey/issues/14#issuecomment-1346882195) to be the main source of data and just return that data with minimal changes to fit `searvey` API conventions?

**Comment by cheginit** [comment]
@mroberge, Thanks for mentioning HyRiver. As Martin said, [PyGeoHydro](https://github.com/hyriver/pygeohydro) includes a class called [NWIS](https://github.com/hyriver/pygeohydro/blob/55312a5decce1bdccb93525c7bdd34925c6159e2/pygeohydro/waterdata.py#L34) that provides access to several NWIS endpoints (you can check out [this](https://docs.hyriver.io/examples/notebooks/nwis.html) example notebook). Also, I developed robust and performant engines for working with web services ([AsyncRetriever](https://github.com/hyriver/async-retriever) and [PyGeoOGC](https://github.com/hyriver/pygeoogc)), so feel free to explore them and let me know if you need any help.

**Comment by SorooshMani-NOAA** [comment]
@cheginit I learned about your toolset a couple of weeks ago when working on a different project. Your software stack is very impressive and useful, however since `searvey` is focused on giving access to the original data from the source at the lowest level, it makes more sense to use minimal packages like `dataretrieval`. With that being said, I'm looking forward to using your software stack in other projects.

**Comment by SorooshMani-NOAA** [comment]
@brey, @pmav99, @saeed-moghimi-noaa, if you haven't already, I highly recommend reading this summary by @mroberge: https://github.com/mroberge/hydrofunctions/issues/79. (mentioned in https://github.com/oceanmodeling/searvey/issues/14#issuecomment-1346882195)

After that I'd like us to re-evaluate why we want to add USGS support within `searvey`. My take is:
- `searvey` is a one-stop shop for \[original\] measurement data used for validating coastal ocean models
- `dataretrieval` returns the data in a form very close to original source (NWIS REST API)
- We don't want to reimplement the wheel

I'm just thinking out load, but given above (as opposed to what I said to @pmav99 the other day) maybe it makes more sense to follow the original plan of using `dataretrieval` package, and just assume the return values are the original data from source.

What do you think?

**Comment by saeed-moghimi-noaa** [comment]
@SorooshMani-NOAA 

What you suggested make sense.  I am fine with that. However I will let @brey and @pmav99 as the lead developers of searvey to have the final say.

Thanks,

**Comment by brey** [comment]
After the discussion with @SorooshMani-NOAA few days back and seeing his progress (!) using `dataretrieval` let's go with that. Thanks Soroosh.

I will close this issue and we can open more specific ones if needed during the implementation.
