### ISSUE TITLE
What is the maximum number of requests that we can send to IOC and COOPS (rate limiting)?

### ISSUE THREAD

**Issue by pmav99** [oceanmodeling/searvey#27]
In order to speed up data retrieval, it makes sense to parallelize the requests for the station data - e.g. using `async` or `multithreading`. Nevertheless I couldn't find any reference WRT rate limiting in the respective websites.  Does anyone know what is the maximum number of concurrent requests that we can send to IOC and COOPS without violating their ToS? 

https://api.tidesandcurrents.noaa.gov/api/prod/
https://www.ioc-sealevelmonitoring.org/disclaimer.php

Do we know anyone that we could ask?

**Comment by bart-v** [comment]
For IOC, there currently is no strict/hard limit in place.
But if you do a massive amount of concurrent request and prevent other users to use the system, you will be blocked.
Therefore, we suggest you keep it to 5 concurrent requests maximum

**Comment by pmav99** [comment]
That's great, thank you @bart-v

**Comment by brey** [comment]
I think we can close this one
