### ISSUE TITLE
Simplify the COOPS stations API 

### ISSUE THREAD

**Issue by pmav99** [oceanmodeling/searvey#29]
Currently there are 3 different functions for retrieving the COOPS station data:

``` python
coops_stations()
coops_stations_within_region()
coops_stations_within_bounds()
```

I think that these functions could be merged in a single function with something like the following signature:

``` python
def coops_stations(
    region: Optional[Union[Polygon, MultiPolygon]] = None,
    lon_min: Optional[float] = None,
    lon_max: Optional[float] = None,
    lat_min: Optional[float] = None,
    lat_max: Optional[float] = None,
    station_status: Optional[StationStatus] = None
) -> pd.DataFrame
```
The idea is that:

- if neither `region` nor the BBox are specified, then all the stations are returned. This should be the default behavior.
- if only `region` is specified then the stations outside of the region are filtered out
- if only BBox is specified then the stations outside of the BBox are filtered out
- if both `region` and BBox are specified then an exception is raised

@zacharyburnett what do you think?

**Comment by zacharyburnett** [comment]
That's a good idea, however we can make it simpler by removing the bbox specification entirely (only keep `region` and `station_status`) and write in the docstring to use `shapely.geometry.box()` for a bounding box

**Comment by pmav99** [comment]
Sure, I just let it because I thought you might need it somewhere in StormEvents or something

**Comment by brey** [comment]
Is this issue still relevant?
