### ISSUE TITLE
Tests fail on OSX

### ISSUE THREAD

**Issue by brey** [oceanmodeling/searvey#35]
The `os.sched_getaffinity(0)` used in `multi.py` is only available for `linux` (not `osx` nor `windows`).

https://docs.python.org/3/library/os.html#interface-to-the-scheduler

**Comment by pmav99** [comment]
When you run `python -c 'import os; print(os.sched_getaffinity(0))'` what exception do you get? `AttributeError`?

**Comment by brey** [comment]
`❯ python -c 'import os; print(os.sched_getaffinity(0))'

Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'os' has no attribute 'sched_getaffinity'
`
