### ISSUE TITLE
Implementing light wrapper around `Dataframe`s and `Dataset`s

### ISSUE THREAD

**Issue by SorooshMani-NOAA** [oceanmodeling/searvey#42]
Right now since all the functions return basic `Dataframe` and `Dataset` objects, it is not possible to chain call some methods for easier access. The following snippet demonstrates what I mean
```python
    stations = coops.coops_stations_within_region(region=bbox)
    data = coops.coops_product_within_region(
        'water_level', region=bbox, start_date=start, end_date=end)
```
In this case stations dataframe has some information not included in `data` object, e.g. `name`. If we have a lightweight wrapper around these return values, then some additional functionality can be provided to do something like this:
```python
    stations = coops.coops_stations_within_region(region=bbox)
    data = stations.get_product('water_level',  start_date=start, end_date=end)
```
As well as more sophisticated functionality such as normalizing, vdatum, etc. In this case the raw underlying data can be provided by a `.raw` or `.data` method or property of the light wrapper.

Of course I understand this goes against the idea of providing light API to get raw data for the user. So maybe this functionality could go to a downstream package that lightly wraps `searvey`.

**Comment by pmav99** [comment]
> The following snippet demonstrates what I mean ...

To be precise, in your example of the existing API there is no need to call `coops_stations_within_region()`. You can just call `coops_product_within_region()` and you will get the data.

That being said, I am not a huge fan of such a design:

1. More code to write, more code to test, more code to maintain. Furthermore, from the user's perspective, more APIs to learn.
2. Such an API would be very much COOPS specific. I doubt it would be feasible to implement this extra functionality for different providers, therefore we would end up with different APIs for each provider. I would be much more inclined to try to merge the APIs instead.
3. I am not convinced that the number of users of searvey is such that justifies the creation of super user-friendly abstractions. 

For me the API should be something like this:

``` python
stations = get_coops_stations(region=my_polygon)
# Optionally filter stations according to **your** criteria. 
# For example you may be interested only in Florida stations:
# stations = stations[stations.state == "FL"]
data = get_coops_data(stations=stations, product="water_level")
```

This is easy to write, easy to test, easy to understand, it only consists of a couple function calls and is pretty much provider agnostic, users only need to know pandas/xarray which I assume that they already do, and if not then they will learn something which they can reuse in the future.

That being said, "code wins arguments". If you feel like it, do make a PR and even if we don't merge it could live as a downstream package providing a higher level API.

PS. We already have one more issue for the COOPS API: https://github.com/oceanmodeling/searvey/issues/29

**Comment by SorooshMani-NOAA** [comment]
I think your suggestion for having a `get_coops_data(...)` function makes sense. What I was trying to say in my example was that let's assume we need to use information from both `stations` and `data`, if so, then we need to do the `get_*_within_region` twice. If the API supports passing return value from one function to another in order to get more information (e.g. pass `stations` to a function to get `data`) that's equivalent to what I'm asking for, with less maintenance overhead and smaller API for user to learn.

**Comment by pmav99** [comment]
@SorooshMani-NOAA I think we can close, if there is anything else, please do reopen.
