### ISSUE TITLE
dtype Category not writeable 

### ISSUE THREAD

**Issue by brey** [oceanmodeling/searvey#44]
https://github.com/oceanmodeling/searvey/blob/0b0e372b6b1a33886b0e224dc0195a2e8a0f16dd/searvey/ioc.py#L150

The above referenced normalization creates a problem when trying to save to `(geo)json`.

Ex.

```python
from searvey import ioc
import shapely
geo_box = shapely.geometry.box(-25.0, 56.0, -12.0, 74.0)
tg = ioc.get_ioc_stations(region=geo_box)
tg.dtypes
tg.to_file('stations.json')
```

Setting 

```python
tg['country']=tg.country.astype('str')
```

solves the problem. 

Maybe this should be included in the final output on `searvey` side? I am not sure why `category` `dtype` is needed.

**Comment by pmav99** [comment]
Sure. Category is just a RAM/speed optimization, but if it causes compatibility issues, we can live without it.
