### ISSUE TITLE
Rate limit object and multi processing/threading

### ISSUE THREAD

**Issue by SorooshMani-NOAA** [oceanmodeling/searvey#53]
In IOC code at:
https://github.com/oceanmodeling/searvey/blob/0fc8bae89b7ffef7862ae1367f41dd90e2d4fd4c/searvey/ioc.py#L327-L344

is the `RateLimit` object shared between all the threads or a new copy is created for each one? If the latter is true, then it might not work as intended.

**Comment by pmav99** [comment]
The `rate_limit` object should be an instance of the `RateLimit` class. If no object is passed then the default `rate_limit` object is used (and which should allow up to 5 requests / sec). This class is a wrapper for the [limits](https://github.com/alisaifee/limits/) library and [should be thread safe](https://github.com/alisaifee/limits/issues/26).

That being said, this is the first time I've used this library so there might be caveats I am not aware of. Did you run into any issues with the threads? Did you perhaps notice more than 5 requests per second?

**Comment by pmav99** [comment]
The purpose of the `RateLimit` class was to allow for a "nice" UI like the following: https://github.com/oceanmodeling/searvey/blob/0fc8bae89b7ffef7862ae1367f41dd90e2d4fd4c/searvey/ioc.py#L259-L261

(`rate_limit` is an instance of `RateLimit`)

**Comment by SorooshMani-NOAA** [comment]
Thank you for the explanation. I haven't encountered any issues with it, but as I was looking at the code, I wanted to make sure I understand the implications. I know for multi processing the objects passed as arguments are copied, so usually more care is needed but I was not sure about threads. I think it'd be good to close and keep this issue as a clarification question and later if any actual issue is encountered we can reopen it and discuss.
