### ISSUE TITLE
USGS improvements

### ISSUE THREAD

**Issue by pmav99** [oceanmodeling/searvey#65]
Notes from today's meeting

- [x] Add a `state` column
- [x] If possible, `get_usgs_stations()` should contain a column with the data_type/variable.
- [x] `get_usgs_stations(region)` should retrieve all the stations and use region to filter them. Now it uses the "region" USGS API and this is limiting the number of stations we can retrieve.
- [x] we should add USGS data to `searvey.stations.get_stations()`
- [x] Add new parameters to the data fetched (https://github.com/oceanmodeling/searvey/issues/65#issuecomment-1450395251)

**Comment by SorooshMani-NOAA** [comment]
> we should add USGS data to `searvey.stations.get_stations()`

@pmav99, @carolakaiser I'm not sure if I'm using the best indicator for `is_active`, but I kind of just followed `IOC`. We can discuss if this makes sense or not during our next meeting

**Comment by SorooshMani-NOAA** [comment]
@carolakaiser, @pmav99, I'm done with changes for the USGS. You can test it in `enhance/usgs-cera` branch if you'd like. I'll discuss the details in the observation data meeting on Wednesday. Thanks!

**Comment by SorooshMani-NOAA** [comment]
Process:
1. Get by parameters
2. Get by region (coastal)
3. Adjust by vertical datum
4. Adjust time zone
5. Station active vs inactive

**Comment by SorooshMani-NOAA** [comment]
Notebook https://github.com/SorooshMani-NOAA/searvey/blob/enhance/usgs-cera/examples/CERA_workflow.ipynb added for workflow example
