### ISSUE TITLE
Avoid function calls as default arguments in functions

### ISSUE THREAD

**Issue by pmav99** [oceanmodeling/searvey#66]
Function calls should be avoided as default aguments. 

``` python
import datetime
import time

def print_isotime(timestamp: datetime.datetime = datetime.datetime.now()) -> None
    print(timestamp.isoformat())

for i in range(3):
    print_isotime()
    time.sleep(1)
```
The above snippet will print:
```
2023-03-03T12:15:00.714514
2023-03-03T12:15:00.714514
2023-03-03T12:15:00.714514
```
I.e the timestamps do not change. This happens due to early bounding of function arguments]and is a [well known gotcha](https://rednafi.github.io/reflections/gotchas-of-early-bound-function-argument-defaults-in-python.html)

We use this anti-pattern in IOC and USGS. I introduced it and I guess that @SorooshMani-NOAA just followed my lead.
https://github.com/oceanmodeling/searvey/blob/f7763c6ae4faf940508f3320023573e928bf53f6/searvey/ioc.py#L252

https://github.com/oceanmodeling/searvey/blob/f7763c6ae4faf940508f3320023573e928bf53f6/searvey/usgs.py#L280

In practical terms this is a problem, because in a long running script, after midnight the date will not be updated.

There are several ways to avoid this. The most common one is to use `None` as the default value and make the function call in the body of the function. E.g.:
``` python
def print_time(timestamp: datetime.datetime | None = None) -> None
    if timestamp is None:
        timestamp = datetime.datetime.now()
    print(timestamp.isoformat())
```

Nevertheless, this is not ideal when the code is being statically typed, because you change the signature. Anyhow, we should remove it.

**Comment by SorooshMani-NOAA** [comment]
Interesting point. Thanks for catching the issue!
