### ISSUE TITLE
Adding functionality to download obs in format compatible with OCS's autoval code

### ISSUE THREAD

**Issue by gseroka** [oceanmodeling/searvey#68]
@SorooshMani-NOAA  

Spoke with Saeed today about linking searvey with OCS's autoval (https://github.com/noaa-ocs-modeling/autoval), using the Pacific SCHISM model as a test case. Autoval uses csdllib (https://github.com/noaa-ocs-modeling/csdllib) to download CO-OPS observed water level data. 

The specific piece of code in csdllib that does this is 
https://github.com/noaa-ocs-modeling/csdllib/blob/master/csdllib/data/coops.py -- the getData function (see below).

A sample URL that it downloads is https://opendap.co-ops.nos.noaa.gov/axis/webservices/waterlevelrawsixmin/plain/response.jsp?stationId=8410140&beginDate=20230302%2018:06&endDate=20230310%2012:00&datum=MSL&unit=0&timeZone=0&Submit=Submit

8410140 1 WL 2023-03-02 18:06  -1.868   0.017   1 0 0 0
8410140 1 WL 2023-03-02 18:12  -1.887   0.007   1 0 0 0
8410140 1 WL 2023-03-02 18:18  -1.901   0.010   0 0 0 0
8410140 1 WL 2023-03-02 18:24  -1.905   0.008   1 0 0 0
8410140 1 WL 2023-03-02 18:30  -1.910   0.010   1 0 0 0
8410140 1 WL 2023-03-02 18:36  -1.914   0.009   1 0 0 0
8410140 1 WL 2023-03-02 18:42  -1.923   0.009   0 0 0 0

Would you be able to add capability to searvey to download CO-OPS (and eventually IOC and USGS) observations into this format?

```
def getData (stationID,  dateRange, tmpDir=None,
             product='waterlevelrawsixmin', datum='MSL', units='meters', verbose=False):
    
    Allows for downloading the observations from NOAA's 
    Center for Operational Oceanographic Products and Services (COOPS)
    via OpenDAP server    http://opendap.co-ops.nos.noaa.gov .
    
    Args:
        stationID (str):              7 character-long CO-OPS station ID.
        dateRange (datetime, datetime): start and end dates of retrieval.
```

**Comment by SorooshMani-NOAA** [comment]
@gseroka it should be straightforward to add, since we already download the data from all the stations, I think it can be some kind of a utility function. The biggest thing to consider is whether we'd like it to be a part of `searvey` or the client code; i.e. I can write a function that uses `searvey` to achieve what you want and pass it to you to include it as a part of `autoval`.

@pmav99, what's you're view on this?

**Comment by gseroka** [comment]
Thanks so much Soroosh!

--

Greg Seroka, Ph.D.

Physical Scientist

Coastal Marine Modeling Branch

NOAA/NOS/OCS/Coast Survey Development Laboratory

1315 East West Hwy, SSMC3 Rm 6839, N/CS13

Silver Spring, MD 20910-3282

Phone: (240) 847-8272

**Comment by gseroka** [comment]
Thanks so much @SorooshMani-NOAA. 

1. Yes, ```water_level``` only for now. We may eventually expand ```autoval``` / ```csdllib``` to validate other variables, e.g. currents, but that is in the future.
2. 6-minute intervals is what is needed now for ```autoval``` / ```csdllib```
3. To my knowledge, this will always be 1. Please see the below links:
     https://opendap.co-ops.nos.noaa.gov/axis/webservices/waterlevelrawsixmin/response.jsp?stationId=8410140&beginDate=20230302&endDate=20230310&datum=MSL&unit=0&timeZone=0&format=text&Submit=Submit
     https://opendap.co-ops.nos.noaa.gov/axis/webservices/waterlevelrawsixmin/index.jsp
     https://opendap.co-ops.nos.noaa.gov/axis/webservices/
4. For now, no, we do not need the full functionality of ```csdllib```, just the ```getData``` function, and just for water levels now

**Comment by SorooshMani-NOAA** [comment]
@gseroka please see https://github.com/SorooshMani-NOAA/searvey/blob/example/ocs-autoval/examples/OCS-Autoval.ipynb for the first example of how to format `searvey` coops data into what you need it to look like. 

Please let me know if you need help with setting up `searvey` environment. This notebook example can simply be written in a function that you can call for `autoval`

**Comment by gseroka** [comment]
Thank you @SorooshMani-NOAA! Will test out at some point hopefully soon!

**Comment by SorooshMani-NOAA** [comment]
@gseroka have you had a chance to look into this?

**Comment by gseroka** [comment]
@SorooshMani-NOAA not yet. Lei is working on getting STOFS-3D-Pacific up and running in semi-operational mode, and then will look into hooking up searvey with autoval to do the skill assessment for it. Thanks again for doing this!

**Comment by SorooshMani-NOAA** [comment]
OK thank you, no problem!

**Comment by SorooshMani-NOAA** [comment]
Are there any updates on this front? Should I close this ticket?

**Comment by gseroka** [comment]
Hi Soroosh, yes, please close this ticket. We still haven't had a chance to
test yet due to operational priorities. I'm thinking Lei should have a
chance in the coming months. Thank you for your work on it!! Once he
works on it, we can reopen the issue if needed.

--

Greg Seroka, Ph.D.

Physical Scientist

Coastal Marine Modeling Branch

NOAA/NOS/OCS/Coast Survey Development Laboratory

1315 East West Hwy, SSMC3 Rm 6839, N/CS13

Silver Spring, MD 20910-3282

Phone: (240) 847-8272
