### ISSUE TITLE
Station activity status

### ISSUE THREAD

**Issue by brey** [oceanmodeling/searvey#73]
https://github.com/oceanmodeling/searvey/blob/aa5a64050576bb7d248b19b281e5e233cfb28c28/searvey/stations.py#L75

Currently we define a station as active in a very ad-hoc way. COOPS has an upstream definition while a time threshold is used for IOC (see above).

We need to come up with a consistent definition or avoid the tag altogether and let the user subset the data after retrieval.

**Comment by pmav99** [comment]
We now have the `is_active` column in `searvey.get_stations()`

Closing.
