### ISSUE TITLE
Make the example Notebooks binder friendly

### ISSUE THREAD

**Issue by brey** [oceanmodeling/searvey#76]
Both the IOC and COOPS Notebooks work fine on `Binder`. The CERA one produces some errors and the USGS_data crashes the kernel most likely due to the memory constrain. Note that binder has a ceiling of 2GB of memory. 

@SorooshMani-NOAA Can you have a look and push some new versions of the notebooks? There is no need of a release since the Notebooks are read from the repo.

**Comment by SorooshMani-NOAA** [comment]
The `NaT` issue seems to be coming from an update in `pandas`. Version `2.0.0` was recently released, and the result of the `to_datetime` in the following calls is `NaT`. This used to return valid dates before.

https://github.com/oceanmodeling/searvey/blob/f4a29d5b6063d5d1f6db7809f5b71b3227c7217b/searvey/usgs.py#L129-L130
