### ISSUE TITLE
CERA_worklow.ipynb is broken

### ISSUE THREAD

**Issue by pmav99** [oceanmodeling/searvey#79]
@SorooshMani-NOAA I tried to execute the `CERA_workflow.ipynb` notebook and it seems that it is broken. You get a traceback in cell 7, but the root problem is in cell 6:

``` python
usgs_stations_w_param = usgs_stations[usgs_stations.parm_cd.isin(params_of_interest)]
is_active = (datetime.now() - usgs_stations_w_param.end_date) < timedelta(days=3)
usgs_stations_of_interest = usgs_stations_w_param[is_active]
```
More specifically the `end_date` of `usgs_station_w_param` is `NaT` for all rows, and as a result `usgs_stations_of_interest` is an empty dataframe. This causes the next cell which does the actual plotting to fail. 

Can you have a look?

**Comment by pmav99** [comment]
Actually this seems to be a pandas 2 issue. Something seems to have changed. I just installed pandas 1.5.3 and the cell runs fine. Probably something with the parsing of `end_date`?

**Comment by SorooshMani-NOAA** [comment]
Aren't these addressed in #77 which is pending merge?

**Comment by pmav99** [comment]
You are right, this will be fixed as soon as #77 gets merged. Closing

**Comment by carolakaiser** [comment]
Hey All,
I am trying to retrieve the USGS stations for the CERA workflow and I am just running the following two lines (in a python script, python version is 3.10):

from searvey import usgs, stations
usgs_stations = usgs.get_usgs_stations()

I get a pretty lengthy error log - any idea what that could be? Thanks!

[usgs_test_error.log](https://github.com/oceanmodeling/searvey/files/11548732/usgs_test_error.log)

**Comment by pmav99** [comment]
This is a separate issue, so I opened a new ticket. Closing this one.
