### ISSUE TITLE
Move "get data" functionality from `StormEvents` to `searvey`

### ISSUE THREAD

**Issue by SorooshMani-NOAA** [oceanmodeling/searvey#8]
@zacharyburnettNOAA @pmav99 @brey  what is the plan to move "get data" functionality of `StormEvents` to `searvey`? 

Should there be standardized input parameters and output `dataframe` for all data sources in `searvey`? In that case, for example, does it make sense to move USGS high water mark to `searvey`? As it has `event_id` as input and output `dataframe` that has non-station locations based on input county and state. Also how should dataframes be indexed?

**Comment by zacharyburnettNOAA** [comment]
HWM data does have point data (XY locality) so it could fit into `searvey`'s current structure of point-based data

I think continuing to use `DataFrame` as a standard output is a good idea. I have been using classes and inheritance to implement a common standard among data getters; we could create an abstract base class (ABC) that encompasses the abstract idea of "gettable data source"

**Comment by brey** [comment]
I agree with using the `DataFrame` as data structure of choice. We need to identify what part of `StormEvents`, namely the retrieval process, should be externalised and integrated into `searvey`.  However, this correlates to the discussion on the structure of `searvey` (#12) and we need to sort them together.

**Comment by brey** [comment]
I think this is done. Issue #42 notwithstanding.
