### ISSUE TITLE
windows and multiprocessing

### ISSUE THREAD

**Issue by pmav99** [oceanmodeling/searvey#85]
Hey All,
I am trying to retrieve the USGS stations for the CERA workflow and I am just running the following two lines (in a python script, python version is 3.10):

```
from searvey import usgs, stations
usgs_stations = usgs.get_usgs_stations()
```

I get a pretty lengthy error log - any idea what that could be? Thanks!

[usgs_test_error.log](https://github.com/oceanmodeling/searvey/files/11548732/usgs_test_error.log)

_Originally posted by @carolakaiser in https://github.com/oceanmodeling/searvey/issues/79#issuecomment-1560193894_

**Comment by pmav99** [comment]
Hi Carola, the error is probably due to you running this on windows. It seems that multiprocessing is behaving somewhat differently there. AFAIK no one has tested searvey on windows yet.

pinging @SorooshMani-NOAA

**Comment by SorooshMani-NOAA** [comment]
@carolakaiser, how do you run the two lines above? Do you have them in a files and then you call `python scriptfile.py`? If so, can you please make the following modification to the script file:
```diff
  from searvey import usgs, stations
- usgs_stations = usgs.get_usgs_stations()
+ if __name__ == '__main__':
+     usgs_stations = usgs.get_usgs_stations()
```
and see if it fixes the issue?

**Comment by carolakaiser** [comment]
OK, great, this is progress. First error messages are gone. 

Now I get this:

  df = pd.read_csv(StringIO(rdb), delimiter='\t', skiprows=count + 2,                                                                                         C:\Python310\lib\site-packages\dataretrieval\nwis.py:1167: DtypeWarning: Columns (6,16) have mixed types. Specify dtype option on import or set low_memory=False.                                                                                                                                                             df = pd.read_csv(StringIO(rdb), delimiter='\t', skiprows=count + 2,

**Comment by SorooshMani-NOAA** [comment]
This seems to be a harmless warning (maybe just relevant for performance?). I don't think this warning should interrupt the workflow. If you get a value for `df` it should be fine to use it.

**Comment by carolakaiser** [comment]
Hi Soroosh, thank you for the information. I am now able to retrieve the complete (unfiltered) USGS dataset. I will continue with more filtering and keep you in the loop. Thanks again.

**Comment by carolakaiser** [comment]
Reading in a shapefile:
An error occurred: (<class 'geopandas.geoseries.GeoSeries'>, <class 'str'>)                                                                                   ['  File "D:\\Projects\\searvey\\test.py", line 32, in <module>\n    get_csv()\n', '  File "D:\\Projects\\searvey\\test.py", line 16, in get_csv\n    usgs_stations = usgs.get_usgs_stations(region=region_of_interest)\n', '  File "D:\\Projects\\searvey\\searvey\\usgs.py", line 219, in get_usgs_stations\n    usgs_stations = usgs_stations[usgs_stations.within(region)]\n', '  File "C:\\Python310\\lib\\site-packages\\geopandas\\base.py", line 1758, in within\n    return _binary_op("within", self, other, align)\n', '  File "C:\\Python310\\lib\\site-packages\\geopandas\\base.py", line 59, in _binary_op\n    data, index = _delegate_binary_method(op, this, other, align, *args, **kwargs)\n', '  File "C:\\Python310\\lib\\site-packages\\geopandas\\base.py", line 41, in _delegate_binary_method\n    raise TypeError(type(this), type(other))\n']

**Comment by carolakaiser** [comment]
This references to a discussion I just had with Panos in the meeting, he has made some suggestions that I will try out before reporting back again. Thanks.
