### ISSUE TITLE
usgs tests are flaky

### ISSUE THREAD

**Issue by pmav99** [oceanmodeling/searvey#86]
This test is currently failing:

https://github.com/oceanmodeling/searvey/blob/2a510e953a2799047553f1c253d8990141ab8906/tests/usgs_test.py#L90-L105

with:
```
=============================================================================================================== FAILURES ===============================================================================================================
__________________________________________________________________________________________ test_get_usgs_station_data[truncate_seconds=False] __________________________________________________________________________________________
tests/usgs_test.py:105: in test_get_usgs_station_data
    assert len(df) == no_records
E   assert 18 == 11
```

The dataframe we get is:
``` python
df = usgs.get_usgs_station_data(
    usgs_code="15484000",
    endtime=datetime.date(2022, 10, 1),
    period=1,
    truncate_seconds=False,
)
```
``` 
                                                                  value qualifier unit                                               name
site_no  datetime                  code  option                                                                                          
15484000 2022-09-30 08:00:00+00:00 00065                           7.32         A   ft                                  Gage height, feet
         2022-09-30 16:30:00+00:00 00065                           7.31         A   ft                                  Gage height, feet
         2022-10-01 00:00:00+00:00 00065                            7.3         A   ft                                  Gage height, feet
         2022-10-01 02:30:00+00:00 00065                           7.28         A   ft                                  Gage height, feet
         2022-10-01 04:15:00+00:00 00065                           7.29         A   ft                                  Gage height, feet
         2022-10-01 19:00:00+00:00 00065                           7.27         A   ft                                  Gage height, feet
         2022-10-02 03:15:00+00:00 00065                           7.26         A   ft                                  Gage height, feet
         2022-09-30 08:00:00+00:00 00065 ak dot&pf bridge datum  639.04         P   ft                                  Gage height, feet
         2022-09-30 16:30:00+00:00 00065 ak dot&pf bridge datum  639.03         P   ft                                  Gage height, feet
         2022-10-01 00:00:00+00:00 00065 ak dot&pf bridge datum  639.02         P   ft                                  Gage height, feet
         2022-10-01 02:30:00+00:00 00065 ak dot&pf bridge datum   639.0         P   ft                                  Gage height, feet
         2022-10-01 04:15:00+00:00 00065 ak dot&pf bridge datum  639.01         P   ft                                  Gage height, feet
         2022-10-01 19:00:00+00:00 00065 ak dot&pf bridge datum  638.99         P   ft                                  Gage height, feet
         2022-10-02 03:15:00+00:00 00065 ak dot&pf bridge datum  638.98         P   ft                                  Gage height, feet
         2022-09-30 08:25:00+00:00 72414 ak dot&pf bridge datum   632.3         P   ft  Streambed elevation at measurement point, abov...
         2022-09-30 08:55:00+00:00 72414 ak dot&pf bridge datum  632.21         P   ft  Streambed elevation at measurement point, abov...
         2022-09-30 12:55:00+00:00 72414 ak dot&pf bridge datum  632.12         P   ft  Streambed elevation at measurement point, abov...
         2022-09-30 14:55:00+00:00 72414 ak dot&pf bridge datum  632.38         P   ft  Streambed elevation at measurement point, abov...
[18 rows x 4 columns]
```

-------

I guess that USGS started to return the additional 7 rows recently. Judging from the output, the extra rows that cause the issue are the first 7 ones, i.e. the ones without an `option`.

Is it normal for USGS to add data like this?

Anyhow, this specific test does not seem to be testing what it is supposed to test (i.e. truncate_seconds), because the timestamps don't contain any seconds anyhow. We should probably choose a different combination of `usgs_station` and/or time period.  Furthermore, it will probably be more robust if we make the assertion like this:

``` python
df = usgs.get_usgs_station_data(..., truncate_seconds=False)
df_trunc = usgs.get_usgs_station_data(..., truncate_seconds=True)
assert len(df) > len(df_trunc)

seconds_trunc = df.index.to_frame().datetime.dt.second
assert (seconds_trunc == 0).all()
assert df_with
```

pinging @SorooshMani-NOAA 

PS. There are more tests that are failing, probably due to USGS returning extra data but I didn't dig in deeper in those.
```
FAILED tests/usgs_test.py::test_get_usgs_station_data[truncate_seconds=True] - assert 18 == 11
FAILED tests/usgs_test.py::test_get_usgs_station_data[truncate_seconds=False] - assert 18 == 11
FAILED tests/usgs_test.py::test_get_usgs_data[truncate_seconds=True] - AssertionError: assert 226 == 222
FAILED tests/usgs_test.py::test_get_usgs_data[truncate_seconds=False] - AssertionError: assert 226 == 222
FAILED tests/usgs_test.py::test_get_usgs_station_data_by_string_enddate - assert 30 == 17
```

**Comment by SorooshMani-NOAA** [comment]
I agree the tests are flaky and sometimes irrelevant to what the USGS functions do.

Ideally test should not depend on response from a server. I had issues in `stormevents` too when a server was down or its certificate was expired!

I pretty much copied IOC tests and modified them to call USGS. The truncate seconds doesn't really make sense for the USGS data, I don't know if there are any stations where it would be relevant, but I had to add the argument to be compatible with the unified API.

For the additional data that is returned, I don't think there are any good solutions. We might need to just have fixed data that run through those functions and not call the actual data source. Or maybe just don't check length of data and try to test other aspects of data manipulation, e.g. fetched data vs output data frame, etc.

What do you think @pmav99?

**Comment by pmav99** [comment]
If you rely on the responses of remote servers, your tests will be slow and broken whenever the server is down. If on the other hand you mock the responses of remote servers, then, whenever the API changes your tests will keep on passing but your code will be broken. IMHV both approaches are problematic. Choosing what to do is somewhat case specific.

If `truncate_seconds` doesn't make sense for USGS then it should be removed. No reason to complicate the API and for sure no reason to add meaningless tests. 

I think that we should aim to have a unified API focusing on returned objects (e.g. pandas Dataframes) and function names. If possible we should also use same arguments (e.g. no reason not to use `end_date` everywhere) but there is no need to be  pedantic about it. For sure here are going to be some data-provider specific arguments anyway.

Anyhow, I will update the tests so that CI can pass and we can revisit the tests and/or `truncate_timestamps` at a later time.

**Comment by pmav99** [comment]
I don't understand what USGS is doing...
```
Python 3.9 on Ubuntu: All tests passed
Python 3.10 on Macos:  FAILED tests/usgs_test.py::test_get_usgs_stations - assert 34945 > 35000
```
https://github.com/pmav99/searvey/actions/runs/5087897730/jobs/9143712140#step:12:259

**Comment by pmav99** [comment]
I find it hard to believe that it is related to the python version and/or the OS. Not impossible, but hard. Chances are that there is some issue with their servers/software... They just send back different resources.

Is there anyone we could ping from USGS to ask them about it?

**Comment by SorooshMani-NOAA** [comment]
@pmav99 rerunning [lines above](https://github.com/oceanmodeling/searvey/issues/86#issuecomment-1564349413) again resulted in both 3.10 and 3.9 returning `36033` entries! I think it might have something to do with some of the multiprocess responses failing when multiple jobs run at the same time on a single machine!

@thodson-usgs, @elbeejay we are running multiple processes to call the `dataretrieval`'s `get_info` for different parameters and states. We notices that in our automated tests on GitHub and even sometimes on local machine we get different responses in terms of number of station entries. Do you know if there are any limitations on the number of requests a single machine can make simultaneously to USGS API?

**Comment by elbeejay** [comment]
Hi @SorooshMani-NOAA - I pinged our development team about this and they wanted to know what the specific URLs are that you are hitting. From what I saw, this test ultimately calls `dataretrieval.nwis.get_info` for each state? If so, the second object returned by `dataretrieval.nwis.get_info` will be one of our metadata objects which includes the query URL used, which can be accessed as `metadata.url`

So, not sure (yet) of whether or not we have limits on simultaneous requests, but it sounds like with the list of query URLs we might be able to find out what's going on.

**Comment by thodson-usgs** [comment]
There are limits, yes. I'd expect the REST server would throw an error, but their behavior is notoriously inconsistent, and requests for fixes are denied 👎

**Comment by SorooshMani-NOAA** [comment]
@elbeejay @thodson-usgs, thank you for your quick response, and excuse me for the delay. It's good to know that there indeed is a limit. But you're right in saying that this still looks a little different.

What `searvey` does is to call
https://github.com/oceanmodeling/searvey/blob/e51020b16561d30f635e6b031387a99b7080527f/searvey/usgs.py#L116
for each state in a separate process. 

https://github.com/oceanmodeling/searvey/blob/e51020b16561d30f635e6b031387a99b7080527f/searvey/usgs.py#L158-L171

During my tests locally on my machine, I noticed if I do this one time (one Python window) I seem to get the full list of stations returned, but if I do it simultaneously in multiple Python sessions, one of the responses might have a smaller number of stations returned.

This might be an issue either with the limitation or the multiprocessing.

**Comment by elbeejay** [comment]
I agree with the diagnosis that this might not be as straightforward as hitting the API simultaneous request limit. @SorooshMani-NOAA, the service developers asked for the specific URLs being hit as the code is a bit nested to get to the `sites_md` parameter (I also don't know that it is passed along and made accessible?), can you provide those URLs here?

**Comment by elbeejay** [comment]
@SorooshMani-NOAA no clear answers or guidance on this yet, but suggestions and comments have included the following:

> best practices around unit tests would be to mock external calls such as calls to waterservices. It is possible that the site service is returning different numbers of sites as sites are added and removed.

> data coming in from NWIS is always going to be changing. I can't speak to what proportion out of all requested data will be "different"... but all NWIS waterservices does is emit data. The system of record is farther upstream and staff are constantly changing, approving, appending, removing data and stations.
>  
> These folks should probably mock the request tests.

I'm following up to try and get to an answer more specific about rate limits as well as simultaneous queries. Your example above running this process twice in `tmux` is particularly concerning to me. The serial v parallel (multiprocessing) question seems important to answer and maybe creating a set of tests that mock the returns would at least let you be confident that the multiprocessing implementation isn't the problem.

**Comment by SorooshMani-NOAA** [comment]
@elbeejay thank you for your comment. As @pmav99 pointed out there are problems with mocking too, but if the number of items in response from the server can change within a few days/weeks, it makes sense to mock the response with similar format but fixed length responses.

Also about the multiprocessing, I agree that we need to start adding mocked tests to be 100% sure, but for the time being, I can say with high confidence that the functions dealing with submitting and retrieving multiprocess data shouldn't be a direct cause of the problem, as the same methods are being used with other data providers (e.g. IOC).

**Comment by SorooshMani-NOAA** [comment]
@pmav99 I was wondering if it's OK to address removing `truncate_seconds` from USGS API along with the length tests? One of the test related to length just tests truncation effect on the number of entries (none in this case)

Since I was not familiar with the data, I just retrieved data from 7568 stations for 1 day and among the 1782383 entries I got from all stations, all the `datetime.dt.second` values where `0`.

**Comment by pmav99** [comment]
Sure. Just keep it as a separate commit, but no problem if it is part of this PR
